FORMAT: 1A
HOST: https://localhost:3333

# Very Useful Tools to Remenber API

API de acesso a ferramentas. 

# Group API

## Sobre [/]

Proposta através de um desafio da plataforma BossaBox a construção de uma API
para Cadastrar/listar/deletar um conjunto ferramentas no banco de dados com uma estrutura
de dados específica. As principais tecnologias utilizadas nessa API são: MongoDB como banco de dados 
não relacional, Express para controle de requisições e rotas, cors para controle de quais
paginas podem acessar a API, Typescript como linguagem de programação e Node executar os scripts da API.

# Group Tools

## Listar todas as Ferramentas [/list]

### Listar ferramentas [GET]

+ Response 200 (aplication/json)
    + Attributes (ToolUpdate)

## Cadastrar Ferramenta [/tools]

### Cadastrar Ferramenta [POST]

+ Request Cadastrar uma ferramenta no banco de dados
    + Attributes (Tool)

+ Response 201 (aplication/json)
    + Attributes (ToolUpdate)

+ Response 406 (aplication/json)
    + Attributes (Error)

## Listar Ferramenta [/tools?{tag}&{q}]

O campo "tag" não pode estar preenchido sulmultâneamente ao campo "q".
Caso ambos estejam preenchido, apenas o campo tag será considerado.

### Listar Ferramenta [GET]

+ Parameters
    + tag: node (string, optional) - Tag de uma ou varias ferramentas
    + q: Notion (string, optional) - Titulo de uma ou varias ferramentas

+ Response 200 (aplication/json)
    + Attributes (array[ToolUpdate])

+ Response 404 (aplication/json)
    + Attributes (Error)

+ Response 400 (aplication/json)
    + Attributes (Error)

## Deletar Ferramenta [/tools/{id}]

+ Parameters
    + id: 1 (number, required) - ID da ferramenta

### Deletar ferramenta [DELETE]

+ Response 204 (No-Content)

+ Response 404 (aplication/json)
    + Attributes (Error)

# Data Structures

## Tool (object)
+ title (string) - Titulo da ferramentas
+ link (string) - Url da ferramentas
+ description (string) - Descrição da ferramentas
+ tags (array[string]) - Tags da ferramenta

## ToolUpdate (Tool)
+ id (number) - Id da ferramenta

## Error (object)
+ code: 400 (number) - Status code
+ message (string) - Mensagem do status
